services:
  server:
    build: ./multimodalsim-vis/backend
    ports:
      - "8000:8000"
    volumes:
      - ./multimodalsim-vis/backend:/backend
      - /backend/communication/server/node_modules
      - /backend/venv
  multimodalsim-vis:
    build: ./multimodalsim-vis/frontend
    ports:
      - "4200:80"
    volumes:
      - ./multimodalsim-vis/frontend:/frontend
      - /frontend/node_modules
  activemq:
    image: symptoma/activemq:latest
    ports:
      - "61616:61616"
      - "61613:61613"
      - "61614:61614"
      - "8161:8161"
    volumes:
      - ./multimodalsim-vis/backend/communication/activemq.xml:/opt/activemq/conf/activemq.xml
    ulimits:
      nofile:
        soft: 122880
        hard: 122880
    mem_limit: 3g