services:
  server:
    build: ./multimodalsim-vis/backend
    ports:
      - "8000:8000"
    volumes:
      - ./multimodalsim-vis/backend:/backend
      - /backend/communication/server/node_modules
      - /backend/venv
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - multimodalsim_vis_network
    mem_limit: 4g

  multimodalsim-vis:
    build: ./multimodalsim-vis/frontend
    ports:
      - "4200:80"
    volumes:
      - ./multimodalsim-vis/frontend:/frontend
      - /frontend/node_modules
    networks:
      - multimodalsim_vis_network
  activemq:
    image: rmohr/activemq:latest
    ports:
      - "61616:61616"
      - "61613:61613"
      - "61614:61614"
      - "8161:8161"
    ulimits:
      nofile:
        soft: 122880
        hard: 122880
    mem_limit: 3g
    networks:
      - multimodalsim_vis_network

networks:
  multimodalsim_vis_network:
    driver: bridge