services:
  server:
    # image: docker:dind
    privileged: true
    build: ./multimodalsim-vis/backend
    ports:
      - "8000:8000"
    volumes:
      # - ./multimodalsim-vis/backend:/backend
      # - /backend/communication/server/node_modules
      # - /backend/venv
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT=8000
      - ACTIVEMQ=activemq
    mem_limit: 4g
  multimodalsim-vis:
    build: ./multimodalsim-vis/frontend
    ports:
      - "4200:80"
    volumes:
      - ./multimodalsim-vis/frontend:/frontend
      - /frontend/node_modules
  activemq:
    image: symptoma/activemq:latest
    ports:
      - "61616:61616"
      - "61613:61613"
      - "61614:61614"
      - "8161:8161"
    volumes:
      - ./multimodalsim-vis/backend/communication/activemq.xml:/opt/activemq/conf/activemq.xml
    ulimits:
      nofile:
        soft: 122880
        hard: 122880
    mem_limit: 3g
    container_name: activemq

